//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzeriaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderDishes = new HashSet<OrderDishes>();
        }
    
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ComboId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal TotalAmount { get; set; }
        public int PaymentMethodId { get; set; }
        public Nullable<decimal> CashReceived { get; set; }
        public Nullable<decimal> ChangeAmount { get; set; }
    
        public virtual Combos Combos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDishes> OrderDishes { get; set; }
        public virtual PaymentMethods PaymentMethods { get; set; }
        public virtual Users Users { get; set; }
    }
}
